apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build
spec:
  serviceAccountName: tekton-builder
  pipelineRef:
    name: build
  resources:
    - name: repo
      resourceRef:
        name: git-repo
    - name: image
      resourceRef:
        name: target-image-url
