apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: build-webhook
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-gitops-demo-listener
    weight: 100
