apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Release.Name }}-build
spec:
  resources:
    - name: repo
      type: git
    - name: image
      type: image
  tasks:
    - name: build
      taskRef:
        name: buildah-docker-format
        kind: Task
      resources:
        inputs:
          - name: source
            resource: repo
        outputs:
          - name: image
            resource: image
      params:
        - name: FORMAT
          value: "docker"
