apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-webhook
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - bindings:
        - ref: build-params
      template:
        name: build
