kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-tekton-triggers
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
    verbs:
      - get
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      -
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
